name: QuantFlow CI

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"

  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure